# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.3.0"
  python_min: "3.12"
  python_check_max: "3.14"

package:
  name: gaphor
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gaphor/gaphor-${{ version }}.tar.gz
  sha256: 11d8cf0a101c4c9d06e3e0c5b79f31c1d8c17a1b720f28f722153e99e1e24366

build:
  number: 1
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  noarch: python
  python:
    entry_points:
      - gaphor = gaphor.main:main

requirements:
  host:
    - pip
    - poetry-core
    - python ${{ python_min }}.*
  run:
    - __${{ noarch_platform }}
    - adwaita-icon-theme
    - babel >=2.10.3
    - better-exceptions >=0.3.3
    - defusedxml >=0.7.1
    - dulwich >=0.25.0
    - gaphas >=5.1
    - gtk4
    - gtksourceview
    - jedi >=0.18.1,<0.20.0
    - libadwaita
    - pillow >=10.0.0
    - pycairo >=1.22.0
    - pydot >=1.4.2,<4.0.0
    - pygobject >=3.52
    - python >=${{ python_min }}
    - python-generic >=1.0.0
    - tinycss2 >=1.0.2
    - if: osx
      then:
        - pyobjc-framework-cocoa >=9.0.1,<11.0.0

tests:
  - python:
      imports: gaphor
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - gaphor --help
      - gaphor self-test

about:
  summary: Gaphor is the simple modeling tool written in Python.
  license: Apache-2.0
  license_file:
    - LICENSES/Apache-2.0.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/GPL-2.0-or-later.txt
    - LICENSES/LGPL-2.1-or-later.txt
  homepage: https://gaphor.org
  repository: https://github.com/gaphor/gaphor
  documentation: https://docs.gaphor.org

extra:
  recipe-maintainers:
    - danyeaw
